config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admins, skip: %i[registrations passwords], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    get 'homes#top', to: 'admin/sessions#new'

    # items
    resources :items, only: %i[new show index edit create update] do
      get 'search'
    end

    # courses
    resources :courses, only: %i[index edit create update destroy]

    # customers
    resources :customers, only: %i[index edit show update]

    # orders
    resources :orders, only: %i[index show update] do
      resources :order_items, only: %i[index update]
    end
  end

  # 会員
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  #ゲスト
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :customers do
    # homes
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    post 'customers/guest_sign_in',to: 'customers/sessions#cus_sign_in'
    # items
    resources :items, only: %i[show index] do
      resource :favorites, only: %i[create destroy]
      collection do
        get 'search'
      end
    end
    # cart_items
    resources :cart_items, only: %i[index create update destroy] do
      collection do
        delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      end
    end
    # orders
    resources :orders, only: %i[new show index create] do
      collection do
        post 'orders/new' => 'orders#new'
        get 'orders/complete' => 'orders#complete'
      end
    end

    # customers
    resources :customers, only: %i[show edit update] do
      collection do
        get 'customers/leave' => 'customers#leave'
        get :favorites
        patch 'customers/out' => 'customers#out'
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def sum_of_price
    item.add_tax_price * pieces
  end
  scope :items_of_price, -> { inject(0) { |sum, item| sum + item.sum_of_price } }

  def self.caliculate_customer_cart_items(current_customer)
    current_customer.cart_items
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :items, dependent: :destroy

  enum name: { single: 0, randam: 1, season_single: 2, season_randam: 3 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :items, through: :favorites
  has_many :order_items, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }

  #def favorited_items
    #favorites  = current_customer.favorites
    #favorites_items = []
    #favorites.each do |favorite|
      #favorites_items <<= favorite.item
    #end
    #return favorite_items
  #end

  #ゲスト
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
    customer.password = SecureRandom.urlsafe_base64
  end
end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  attachment :image

  Item.left_joins(:favorites)

  validates :item_status, inclusion: [true, false]
  enum course_name: { single: 0, randam: 1, season_single: 2, season_randam: 3 }

  def add_tax_price
    (price * 1.10).round
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :customer

  validates :total_price, presence: true
  enum order_status: { waiting_for_deposit: 0, confirmed_payment: 1, in_production: 2, ready_to_delivery: 3, done: 4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def self.insert_order_item(cart_item, order)
    order_item = new
    order_item.item_id = cart_item.item_id
    order_item.order_id = order.id
    order_item.tax_price = order.total_price
    order_item.number_of_piaces = cart_item.pieces
    order_item.save!
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @item = Item.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to admins_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :item_name, :detail, :price, :item_status, :course_id, :energy, :start, :end,
                                 )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_q
  protect_from_forgery with: :exception
  def after_sign_in_path_for(_resource)
    customer_path(current_customer.id)
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  def require_login!
    redirect_to login_path if session[:customer_email].nil?
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[email first_name last_name password password_confirmation postal_code
                                               address tel])
  end

  def set_q
    @q = Item.ransack(params[:q])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  before_action :move_to_signed_in, except: [:index]
  before_action :set_q, only: [:index, :search, :show]


  def index
    @items = Item.all
    @customer = current_customer
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @favorite_items = current_customer.items.includes(:favorites).order("favorites.created_at DESC")
  end

  def search
    @search = Item.ransack(params[:q])
    @results = @q.result(distinct: true)
  end

  def show
    @item = Item.find(params[:id])
    @order_item = OrderItem.new
    @customer = current_customer
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
  end

  def move_to_signed_in
    unless customer_signed_in?
      redirect_to '/customers/sign_in'
    end
  end

  private
  def set_q
    @q = Item.ransack(params[:q])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admins/carts_helper.rb
module Admins::CartsHelper
end

app/helpers/admins/courses_helper.rb
module Admins::CoursesHelper
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/items/_form.html.erb
<%= form_with model: [:admins, item], local: true do |f| %>
  <table class="mt-5 table justify-content-center">
    <tr>
      <th><%= f.label :image, "商品画像" %></th>
      <td><%= f.attachment_field :image %></td>
    </tr>

    <tr>
      <th><%= f.label :item_name, "商品名" %></th>
      <td><%= f.text_field :item_name, placeholder: "商品名" %></td>
    </tr>

    <tr>
      <th><%= f.label :detail, "商品説明" %></th>
      <td><%= f.text_area :detail, placeholder: "ここに説明文を記述します" %></td>
    </tr>

    <tr>
      <th><%= f.label :course_name, "コース一覧" %></th>
      <td><%= f.select :course_name, {
          "単品注文": 'single',
          "おまかせ注文": 'randam',
          "季節限定単品注文": 'season_single',
          "季節限定おまかせ注文": 'season_randam'
          } %></td>
    </tr>

    <tr>
      <th><%= f.label :price, "税抜き価格" %></th>
      <td><%= f.text_field :price, placeholder: "商品の税別価格を記述して下さい" %></td>
    </tr>

    <tr>
      <th><%= f.label :energy, "エネルギー" %></th>
      <td><%= f.text_field :energy, placeholder: "カロリーを記述して下さい" %></td>

    <tr>
      <th><%= f.label :item_status, '販売ステータス' %></th>
      <td>
        <%= f.radio_button :item_status, :true %>
        <%= f.label :item_status, "販売中" %>
        <%= f.radio_button :item_status,:false %>
        <%= f.label :item_status, "販売停止" %>
      </td>
    </tr>
  </table>

  <div class="row justify-content-center">
    <div class="form-group row">
      <div class="col-sm-4 offset-sm-4 mt-5">
        <%= f.submit yield(:button_text), class:"btn btn-success"%>
      </div>
    </div>
  </div>
<% end %>

app/views/admins/items/edit.html.erb
<% provide(:button_text, "edit") %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 col-xl-6 mx-auto">
      <h2 class="mb-5 ">商品編集</h2>
        <%= render 'form', item: @item %>
    </div>
  </div>
</div>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <h2 class="mb-3">商品一覧</h2>
    </div>
  </div>
    <div class="row">
      <div class="col-12">
        <table class="table">
          <thead class="" style="background-color:#f2c9ac;">
<%= link_to "商品を追加する", new_admins_item_path, class:"far fa-plus-square", :style => "color: black;" %>
            <tr>
              <th>商品ID</th>
              <th></th>
              <th>商品名</th>
              <th>税別価格</th>
              <th>ステータス</th>
              <th></th>
            </tr>
           </thead>


          <tbody class="table-body" style="background-color:#fddea5;">
            <% @item.each do |item| %>

              <tr>
                <td><%= item.id %></td>
                <td><%= attachment_image_tag item, :image, :fill, 100, 100, format: 'jpeg' %></td>
                <td><%= link_to item.item_name, admins_item_path(item.id) %></td>
                <td><%= item.price %></td>
                <td>
                  <% if item.item_status? %>
                    <span class="text-success">販売中</span>
                  <% else %>
                    <span class="text-secondary">販売停止</span>
                  <% end %>
                </td>
                <td><%= link_to "商品を編集する", edit_admins_item_path(item.id),class:"far fa-plus-square", :style => "color: black;" %></td>

              </tr>

            <% end %>

          <div class="col-3 text-right">

        </tbody>
      </table>
    </div>
  </div>
  </div>

app/views/admins/items/new.html.erb
<% provide(:button_text, "create") %>
<h2>商品編集</h2>
   <%= render 'form', item: @item %>

app/views/admins/items/search.html.erb
 <h2>お弁当一覧</h2>
   <%= link_to "", new_admins_item_path %>

   <tr>
     <th>商品ID</th>
     <th>商品名</th>
     <th>税別価格</th>
     <th>ジャンル</th>
     <th>ステータス</th>
    </tr>

  <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= attachment_image_tag item, :image, :fill, 100, 100, format: 'jpeg' %></td>
      <td><%= link_to item.item_name, admins_item_path(item.id) %></td>
      <td><%= item.price %></td>
      <td><%= item.couse.name %></td>
      <td>
        <% if item.item_status %>
          <span class="text-success">販売中</span>
        <% else %>
          <span class="text-secondary">販売停止中</span>
        <% end %>
      </td>
    </tr>
  <% end %>

app/views/admins/items/show.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-12">
      <h2>商品詳細</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 px-3 mb-3 d-flex">
      <%= attachment_image_tag @item, :image, :fill, 500, 500, format: 'jpeg' %>
    </div>
    <div class="col-md-6">
      <table class="table table-borderless">
        <tr>
          <td>お弁当</td>
          <td><%= @item.item_name %></td>
        </tr>

        <tr>
          <td>お弁当説明</td>
          <td><%= @item.detail %></td>
        </tr>

        <tr>
          <td>税込み価格</td>
          <td><%= @item.price %></td>
        </tr>

          <td>熱量</td>
          <td><%= @item.energy %></td>
        </tr>

        <tr>
          <td>販売ステータス</td>
          <td>
          <% if @item.item_status? %>
            <span class="text-success">販売中</span>
          <% else %>
            <span class="text-danger">販売停止中</span>
          <% end %>
            </td>
        </tr>

        <tr>
          <td></td>
          <td>
            <%= link_to "編集する", edit_admins_item_path(@item.id),class: "btn btn-success" %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>