config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admins, skip: %i[registrations passwords], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    get 'homes#top', to: 'admin/sessions#new'

    # items
    resources :items, only: %i[new show index edit create update] do
      get 'search'
    end

    # courses
    resources :courses, only: %i[index edit create update destroy]

    # customers
    resources :customers, only: %i[index edit show update]

    # orders
    resources :orders, only: %i[index show update] do
      resources :order_items, only: %i[index update]
    end
  end

  # 会員
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  #ゲスト
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :customers do
    # homes
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    post 'customers/guest_sign_in',to: 'customers/sessions#cus_sign_in'
    # items
    resources :items, only: %i[show index] do
      resource :favorites, only: %i[create destroy]
      collection do
        get 'search'
      end
    end
    # cart_items
    resources :cart_items, only: %i[index create update destroy] do
      collection do
        delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      end
    end
    # orders
    resources :orders, only: %i[new show index create] do
      collection do
        post 'orders/new' => 'orders#new'
        get 'orders/complete' => 'orders#complete'
      end
    end

    # customers
    resources :customers, only: %i[show edit update] do
      collection do
        get 'customers/leave' => 'customers#leave'
        get :favorites
        patch 'customers/out' => 'customers#out'
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :items, through: :favorites
  has_many :order_items, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }

  #def favorited_items
    #favorites  = current_customer.favorites
    #favorites_items = []
    #favorites.each do |favorite|
      #favorites_items <<= favorite.item
    #end
    #return favorite_items
  #end

  #ゲスト
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
    customer.password = SecureRandom.urlsafe_base64
  end
end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  attachment :image

  Item.left_joins(:favorites)

  validates :item_status, inclusion: [true, false]
  enum course_name: { single: 0, randam: 1, season_single: 2, season_randam: 3 }

  def add_tax_price
    (price * 1.10).round
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def updated_at
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :postal_code, :address, :tel, :is_deleted)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @item = Item.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to admins_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :item_name, :detail, :price, :item_status, :course_id, :energy, :start, :end,
                                 )
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  before_action :move_to_signed_in

  def index
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @order = Order.new
    @customer_cart_items = CartItem.where(customer_id: current_customer.id)
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @item = @cart_item.item

    if @cart_item.save
      redirect_to cart_items_path
    else
      redirect_to item_path(@item)
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])

    redirect_to request.referer if @cart_item.update(cart_item_params)
  end

  def destroy
    @cart_item = CartItem.find(params[:id])

    if @cart_item.destroy
    else
      render :index
    end
  end

  def destroy_all
    redirect_to cart_items_path if CartItem.destroy_all
  end

  def move_to_signed_in
    redirect_to '/customers/sign_in' unless customer_signed_in?
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:customer_id, :item_id, :pieces, :start_date, :end_date)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :ensure_correct_customer, { only: %i[show edit] }

  def show
    @customer = Customer.find(params[:id])
    @orders = current_customer.orders
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @q = Item.ransack(params[:q])
    # favorites = Favorite.where(customer_id: current_customer.id)
    # @favorite_list = Item.find(favorites)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    current_customer.update(customer_params)
    if customer.update(customer_params)
      redirect_to customer_path(current_customer.id)
    else
      render 'edit'
    end
  end

  def leave
    @customer = current_customer
  end

  def out
    @customer = current_customer
    sign_out current_customer if @customer.update(is_deleted: true)
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :tel, :email, :password, :postal_code, :address)
  end

  def ensure_correct_customer
    @customer = Customer.find(params[:id])
    redirect_to root_path if current_customer.id != @customer.id
  end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController
  before_action :set_item

  def create
    @favorite = current_customer.favorites.new(item_id: @item.id)
    @favorite.save
    @favorite_items = current_customer.items.includes(:favorites).order("favorites.created_at DESC")
    @item = @favorite.item
  end

  def destroy
    @favorite = current_customer.favorites.find_by(item_id: @item.id)
    @item = @favorite.item
    @favorite.destroy
    @favorite_items = current_customer.items.includes(:favorites).order("favorites.created_at DESC")
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
  def top; end

  def about; end

end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  before_action :move_to_signed_in, except: [:index]
  before_action :set_q, only: [:index, :search, :show]


  def index
    @items = Item.all
    @customer = current_customer
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @favorite_items = current_customer.items.includes(:favorites).order("favorites.created_at DESC")
  end

  def search
    @search = Item.ransack(params[:q])
    @results = @q.result(distinct: true)
  end

  def show
    @item = Item.find(params[:id])
    @order_item = OrderItem.new
    @customer = current_customer
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
  end

  def move_to_signed_in
    unless customer_signed_in?
      redirect_to '/customers/sign_in'
    end
  end

  private
  def set_q
    @q = Item.ransack(params[:q])
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/order_items_controller.rb
class Customers::OrderItemsController < ApplicationController
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  def new
    @order = Order.new(order_params)
    @cart_item = CartItem.where(customer_id: current_customer.id)
    @customer = current_customer
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
  end

  def create
    @cart_items = current_customer.cart_items
    @order = current_customer.orders.new(order_params)

    if @order.save!
      @cart_items.each do |cart_item|
        OrderItem.insert_order_item(cart_item, @order)
      end

      @cart_items.destroy_all
      redirect_to orders_complete_orders_path
    else
      @order = Order.new(order_params)
      render.new
    end
  end

  def index
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @orders = current_customer.orders
  end

  def show
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @order = Order.find(params[:id])
    @ordered_items = @order.order_items
    @cart_items = current_customer.cart_items.all
  end

  def complete; end

  private

  def order_params
    params.require(:order).permit(:customer_id, :logged_out_on, :total_price, :payment_method, :start_date)
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  def guest_sign_in
    customer = Customer.guest
    sign_in customer
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/views/customers/items/_favorite.html.erb
 <% if item.favorited_by?(current_customer) %>

 <%= link_to item_favorites_path(item), method: :delete,remote: true do %>
    ★お気に入り削除
    <% end %>

  <% else %>

    <%= link_to item_favorites_path(item), method: :post,remote: true do %>
    ☆お気に入りに追加
    <% end %>

  <% end %>

app/views/customers/items/_item.html.erb
<% items.each do |item| %>
  <div class="col-lg-3 col-md-7 mb-5">
    <div class="card-deck" style="width: 19rem;">
      <div class="shadow-sm card">

         <%= link_to item_path(item.id) do %>
           <%= attachment_image_tag item, :image, :fill, 500, 300, fallback: "no-image.jpg",class:"card-img-top" %>
         <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to item.item_name, item_path(item.id) %></h5>
          <p class="card-text"><%= item.detail %></p>
          <h3><%= item.add_tax_price.to_s(:delimited) %>円</h3>
          <button type="button" class="btn btn-outline-warning"><%= link_to "注文する",item_path(item.id) %></button>

          <div class = "favorite" id='item_<%= item.id %>'>
            <%= render '/customers/items/favorite', item: item %>
          </div>

        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/customers/items/index.html.erb
<div class="container" id="items-container">
  <div class="row">
    <h1 class="col-lg-12 text-center">お気に入り商品</h1>
    <div id="favorite_items" class="row col-lg-12">
      <%= render 'item', items: @favorite_items %>
      
    </div>
  </div>

  <div class="row">
    <h1 class="col-lg-12 text-center">商品一覧</h1>
    <%= render 'item', items: @items%>

  </div>
</div>

app/views/customers/items/search.html.erb
<div class="container" id="cartritems-container">
  <h1 class="text title-text">検索結果</h1>
  <div class="row mt-5">
  <table class="table table-bordered table-hover">
   <thead class="table-active text">
     <tr bgcolor="#fce4ec">
       <th>商品名</th>
       <th>商品説明</th>
       <th>熱量</th>
       <th>価格(並盛）</th>
       <th></th>
     </tr>
    <tbody bgcolor="#fcf7f7">
      <% @results.each do |item| %>
       <tr class="light-text">
        <td><%= item.item_name %></td>
        <td><%= item.detail %></td>
        <td><%= item.energy %>kcal</td>
        <td>¥<%= item.add_tax_price.to_s(:delimited) %>(税込)</td>
        <td><%= link_to '詳細を見る', item_path(item.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/customers/items/show.html.erb
<div class="container" id="items-container">
  <div class="col-lg-6 col-md-7 mb-5">
    <div class='col'>
      <%= attachment_image_tag @item, :image, :fill, 500, 500, fallback: "no-image.jpg" %>
    </div>

    <div class='col'>
        <h3><%= @item.item_name %></h3>
        <p><%=  @item.detail %></p>
        <p><%=  @item.energy %>kcal</p>
        <p>価格(並サイズ):¥<%= @item.add_tax_price.to_s(:delimited) %>(税込)</p>

        <%= form_with model: CartItem.new, url: cart_items_path, method: :post do |f| %>
          <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.hidden_field :customer_id, value: current_customer.id %>
            <li>
              <td>並サイズ</td>
              <td><%= f.select :pieces, options_for_select((1..3).to_a) %></td>
              <td>¥<%= @item.add_tax_price.to_s(:delimited) %>(税込)</td>
              <td><%= f.submit "カートに入れる", id: "normal_subumit" %></td>
            </li>
        <% end %>
        <%= form_with model: CartItem.new, url: cart_items_path, method: :post do |f| %>
          <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.hidden_field :customer_id, value: current_customer.id %>

            <li>
              <td>大盛サイズ(約2人前)</td>
              <td><%= f.select :pieces, options_for_select((1..3).to_a) %></td>
              <td>¥<%= (@item.add_tax_price * 1.5).to_i.to_s(:delimited) %>(税込)</td>
              <td><%= f.submit "カートに入れる" %></td>
            </li>
        <% end %>
        <%= form_with model: CartItem.new, url: cart_items_path, method: :post do |f| %>
          <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.hidden_field :customer_id, value: current_customer.id %>

            <li>
              <td>特盛サイズ(約3人前)</td>
              <td><%= f.select :pieces, options_for_select((1..3).to_a) %></td>
              <td>¥<%= (@item.add_tax_price * 2).to_s(:delimited) %>(税込)</td>
              <td><%= f.submit "カートに入れる" %></td>
            </li>
        <% end %>
       </div>
      </div>
     </div>
    </div>
   </div>