config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admins, skip: %i[registrations passwords], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    get 'homes#top', to: 'admin/sessions#new'

    # items
    resources :items, only: %i[new show index edit create update] do
      get 'search'
    end

    # courses
    resources :courses, only: %i[index edit create update destroy]

    # customers
    resources :customers, only: %i[index edit show update]

    # orders
    resources :orders, only: %i[index show update] do
      resources :order_items, only: %i[index update]
    end
  end

  # 会員
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  #ゲスト
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :customers do
    # homes
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    post 'customers/guest_sign_in',to: 'customers/sessions#cus_sign_in'
    # items
    resources :items, only: %i[show index] do
      resource :favorites, only: %i[create destroy]
      collection do
        get 'search'
      end
    end
    # cart_items
    resources :cart_items, only: %i[index create update destroy] do
      collection do
        delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      end
    end
    # orders
    resources :orders, only: %i[new show index create] do
      collection do
        post 'orders/new' => 'orders#new'
        get 'orders/complete' => 'orders#complete'
      end
    end

    # customers
    resources :customers, only: %i[show edit update] do
      collection do
        get 'customers/leave' => 'customers#leave'
        get :favorites
        patch 'customers/out' => 'customers#out'
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def sum_of_price
    item.add_tax_price * pieces
  end
  scope :items_of_price, -> { inject(0) { |sum, item| sum + item.sum_of_price } }

  def self.caliculate_customer_cart_items(current_customer)
    current_customer.cart_items
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :items, dependent: :destroy

  enum name: { single: 0, randam: 1, season_single: 2, season_randam: 3 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :items, through: :favorites
  has_many :order_items, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }

  #def favorited_items
    #favorites  = current_customer.favorites
    #favorites_items = []
    #favorites.each do |favorite|
      #favorites_items <<= favorite.item
    #end
    #return favorite_items
  #end

  #ゲスト
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
    customer.password = SecureRandom.urlsafe_base64
  end
end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  attachment :image

  Item.left_joins(:favorites)

  validates :item_status, inclusion: [true, false]
  enum course_name: { single: 0, randam: 1, season_single: 2, season_randam: 3 }

  def add_tax_price
    (price * 1.10).round
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :customer

  validates :total_price, presence: true
  enum order_status: { waiting_for_deposit: 0, confirmed_payment: 1, in_production: 2, ready_to_delivery: 3, done: 4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def self.insert_order_item(cart_item, order)
    order_item = new
    order_item.item_id = cart_item.item_id
    order_item.order_id = order.id
    order_item.tax_price = order.total_price
    order_item.number_of_piaces = cart_item.pieces
    order_item.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_q
  protect_from_forgery with: :exception
  def after_sign_in_path_for(_resource)
    customer_path(current_customer.id)
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  def require_login!
    redirect_to login_path if session[:customer_email].nil?
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[email first_name last_name password password_confirmation postal_code
                                               address tel])
  end

  def set_q
    @q = Item.ransack(params[:q])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admins/carts_helper.rb
module Admins::CartsHelper
end

app/helpers/admins/courses_helper.rb
module Admins::CoursesHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/couses/edit.html.erb
<h2>コース追加・編集</h2>
  <%= form_with model: [:admins, @couses], local: true do |f| %>
    <%= f.label :name, "コース" %>
    <%= f.text_field :name, placeholder: "コース名を入力" %>
    <%= f.submit '変更を保存' %>
  <% end %>

app/views/admins/couses/index.html.erb
<h2>コース一覧・追加</h2>
  <%= form_with model: [:admins, @couse], local: true do |f| %>
  <%= f.label :name, "コース" %>
  <%= f.text_field :name, placeholder: "ジャンル名を入力" %>
  <%= f.submit '新規登録' %>
  <% end %>

  <tr>
    <th>コース</th>
  </tr>

  <% @couses.each do |genre| %>
  <tr>
    <td><%= couse.name %></td>
    <td>
      %= link_to '編集する', edit_admins_couse_path(couse.id) %>
    </td>
  <% end %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_header.html.erb
<div class='fixed-top'>
 <nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid">
   <% unless admin_signed_in? %>
   <%= render "customers/shared/header" %>
   <% else %>

   <ul class="navbar-nav ml-auto">
    <%= link_to admins_items_path, class: "navbar-brand" do %>
     <%= image_tag 'headlogo.png', { height:50 } %>
   <% end %>

   <h1>管理者ページ</h1>
   <ul class="navbar-nav ml-auto">
    <li class="mr">
     <%= link_to admins_items_path, class: "btn mr-5", style: "background-color: #ffa500; color: white; " do %>
      商品一覧
      <i class="fas fa-utensils"></i>
      <% end %>
   </li>

   <li class="nav-item">
     <%= link_to  admins_customers_path, class: "btn mr-5", style: "background-color: #ffa500; color: white;" do %>
     会員一覧
     <i class="fas fa-book-open"></i>
     <% end %>
   </li>

   <li class="nav-item">
     <%= link_to admins_orders_path(order: 'all'), class: "btn mr-5", style: "background-color: #ffa500; color: white;" do %>
     注文履歴一覧
     <i class="fas fa-cart-plus"></i>
     <% end %>
   </li>

   <li class="nav-item">
     <%= link_to destroy_admin_session_path, method: :delete, class: "btn mr-5", style: "background-color: #ffa500; color: white;" do %>
     ログアウト
     <i class="fas fa-door-open"></i>
     <% end %>
   </li>
   <% end %>
   </ul>
   </nav>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fuwaben</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if controller.class.parent.name == "Admins" %>
      <%= render "admins/shared/header", q: @q %>
    <% else %>
      <%= render "customers/shared/header", q: @q, cart_items: @cart_items %>
    <% end %>
    <%= yield %>
    <%= render "customers/shared/footer", q: @q %>
  </body>
</html>

app/views/layouts/cart_item.js.erb
document.getElementById('cart_items_count').innerHTML = '<%= j(render "customers/shared/header") %>'