config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admins, skip: %i[registrations passwords], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    get 'homes#top', to: 'admin/sessions#new'

    # items
    resources :items, only: %i[new show index edit create update] do
      get 'search'
    end

    # courses
    resources :courses, only: %i[index edit create update destroy]

    # customers
    resources :customers, only: %i[index edit show update]

    # orders
    resources :orders, only: %i[index show update] do
      resources :order_items, only: %i[index update]
    end
  end

  # 会員
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  #ゲスト
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :customers do
    # homes
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    post 'customers/guest_sign_in',to: 'customers/sessions#cus_sign_in'
    # items
    resources :items, only: %i[show index] do
      resource :favorites, only: %i[create destroy]
      collection do
        get 'search'
      end
    end
    # cart_items
    resources :cart_items, only: %i[index create update destroy] do
      collection do
        delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      end
    end
    # orders
    resources :orders, only: %i[new show index create] do
      collection do
        post 'orders/new' => 'orders#new'
        get 'orders/complete' => 'orders#complete'
      end
    end

    # customers
    resources :customers, only: %i[show edit update] do
      collection do
        get 'customers/leave' => 'customers#leave'
        get :favorites
        patch 'customers/out' => 'customers#out'
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :items, through: :favorites
  has_many :order_items, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }

  #def favorited_items
    #favorites  = current_customer.favorites
    #favorites_items = []
    #favorites.each do |favorite|
      #favorites_items <<= favorite.item
    #end
    #return favorite_items
  #end

  #ゲスト
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
    customer.password = SecureRandom.urlsafe_base64
  end
end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def updated_at
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :postal_code, :address, :tel, :is_deleted)
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  before_action :move_to_signed_in

  def index
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @order = Order.new
    @customer_cart_items = CartItem.where(customer_id: current_customer.id)
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @item = @cart_item.item

    if @cart_item.save
      redirect_to cart_items_path
    else
      redirect_to item_path(@item)
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])

    redirect_to request.referer if @cart_item.update(cart_item_params)
  end

  def destroy
    @cart_item = CartItem.find(params[:id])

    if @cart_item.destroy
    else
      render :index
    end
  end

  def destroy_all
    redirect_to cart_items_path if CartItem.destroy_all
  end

  def move_to_signed_in
    redirect_to '/customers/sign_in' unless customer_signed_in?
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:customer_id, :item_id, :pieces, :start_date, :end_date)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :ensure_correct_customer, { only: %i[show edit] }

  def show
    @customer = Customer.find(params[:id])
    @orders = current_customer.orders
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @q = Item.ransack(params[:q])
    # favorites = Favorite.where(customer_id: current_customer.id)
    # @favorite_list = Item.find(favorites)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    current_customer.update(customer_params)
    if customer.update(customer_params)
      redirect_to customer_path(current_customer.id)
    else
      render 'edit'
    end
  end

  def leave
    @customer = current_customer
  end

  def out
    @customer = current_customer
    sign_out current_customer if @customer.update(is_deleted: true)
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :tel, :email, :password, :postal_code, :address)
  end

  def ensure_correct_customer
    @customer = Customer.find(params[:id])
    redirect_to root_path if current_customer.id != @customer.id
  end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController
  before_action :set_item

  def create
    @favorite = current_customer.favorites.new(item_id: @item.id)
    @favorite.save
    @favorite_items = current_customer.items.includes(:favorites).order("favorites.created_at DESC")
    @item = @favorite.item
  end

  def destroy
    @favorite = current_customer.favorites.find_by(item_id: @item.id)
    @item = @favorite.item
    @favorite.destroy
    @favorite_items = current_customer.items.includes(:favorites).order("favorites.created_at DESC")
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
  def top; end

  def about; end

end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  before_action :move_to_signed_in, except: [:index]
  before_action :set_q, only: [:index, :search, :show]


  def index
    @items = Item.all
    @customer = current_customer
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @favorite_items = current_customer.items.includes(:favorites).order("favorites.created_at DESC")
  end

  def search
    @search = Item.ransack(params[:q])
    @results = @q.result(distinct: true)
  end

  def show
    @item = Item.find(params[:id])
    @order_item = OrderItem.new
    @customer = current_customer
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
  end

  def move_to_signed_in
    unless customer_signed_in?
      redirect_to '/customers/sign_in'
    end
  end

  private
  def set_q
    @q = Item.ransack(params[:q])
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/order_items_controller.rb
class Customers::OrderItemsController < ApplicationController
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  def new
    @order = Order.new(order_params)
    @cart_item = CartItem.where(customer_id: current_customer.id)
    @customer = current_customer
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
  end

  def create
    @cart_items = current_customer.cart_items
    @order = current_customer.orders.new(order_params)

    if @order.save!
      @cart_items.each do |cart_item|
        OrderItem.insert_order_item(cart_item, @order)
      end

      @cart_items.destroy_all
      redirect_to orders_complete_orders_path
    else
      @order = Order.new(order_params)
      render.new
    end
  end

  def index
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @orders = current_customer.orders
  end

  def show
    @cart_items = CartItem.caliculate_customer_cart_items(current_customer)
    @order = Order.find(params[:id])
    @ordered_items = @order.order_items
    @cart_items = current_customer.cart_items.all
  end

  def complete; end

  private

  def order_params
    params.require(:order).permit(:customer_id, :logged_out_on, :total_price, :payment_method, :start_date)
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  def guest_sign_in
    customer = Customer.guest
    sign_in customer
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/courses_helper.rb
module Customers::CoursesHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/favorites_helper.rb
module Customers::FavoritesHelper
end

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_footer.html.erb
<div class='fixed-bottom'>
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">
        <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
        <li class="nav-item">


        <li class="nav-item">
          <a class="navbar-brand" href="#">© DMM WEBCAMP 2021 TAKITA YUKIKO</a>
          <%= link_to destroy_customer_session_path, method: :delete, class: "btn mr-5", style: "background-color: #800080; color: white; " do %>
          ログアウト
          <i class="fas fa-door-open"></i>
          <% end %>
        </li>

      <% else %>
      <a class="navbar-brand" href="#">© DMM WEBCAMP 2021 TAKITA YUKIKO</a>
     <% end %>
    </span>
  </div>
</nav>
</div>

app/views/customers/shared/_header.html.erb
<div class='fixed-top'>
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand", data: {"turbolinks" => false} do %>
        <%= image_tag 'headlogo.png', { height:80 } %>
      <% end %>

        <% if customer_signed_in? %>
          <span class="navbar-text">
            ようこそ!<%= current_customer.last_name %>さん
          </span>
          <ul class="navbar-nav ml-auto">
          <li class="mr-1">
            <%= link_to customer_path(current_customer), class: "btn mr-5", style: "background-color: #800000; color: white; " do %>
            カレンダーを見る

            <i class="fas fa-book-open"></i>
            <% end %>
          </li>

            <li class="mr-1">
           <%= link_to  items_path, class: "btn mr-5", style: "background-color: #ffa500; color: white; " do %>
           お弁当を注文する
           <i class="fas fa-utensils"></i>
           <% end %>
        </li>


          <li class="mr-1">
            <%= link_to cart_items_path, class: "btn mr-5", style: "background-color: #800000; color: white; " do %>
              注文に進む
              <i class="fas fa-cart-plus"></i>
              <% if cart_items.present? %>
                  <%= cart_items.count %>
                <% end %>
            <% end %>

            </li>

          <li class="mr-1">
            <%= link_to orders_path, class: "btn mr-5", style: "background-color: #ffa500; color: white; " do %>
            注文履歴
            <i class="fas fa-gift"></i>
            <% end %>
          </li>

           <li class="mx-4">
            <%= search_form_for q, url: search_items_path, class: "form-inline" do |f| %>
              <%= f.search_field:item_name_cont, placeholder: "\uf002" + " 検索", class: "form-control fa" %>
            <%= f.submit '検索' %>
            <% end %>
          </li>

        <% else %>
        <%= link_to "新規会員登録", new_customer_registration_path,class: "btn ", style: "background-color: #e96b22; color: white;" %>
        <%= link_to "会員はこちら", new_customer_session_path, class: "btn", style: "background-color: #cd5c5c; color: white;" %>
        <%= link_to "ゲストログイン（閲覧用）", customers_guest_sign_in_path, method: :post,class: "btn", style: "background-color: #e96b22; color: white;" %>
        <%= link_to "管理者",new_admin_session_path, class: "btn", style: "background-color: #cd5c5c;; color: white;"%>
        <% end %>
      </ul>
    </div>
  </nav>
 </div>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/customers/shared/_search.html.erb
<h1>ユーザー検索</h1>
<%= search_form_for q, url: search_items_path do |f| %>
  <%= f.label :item_cont, 'ユーザー名' %>
  <%= f.search_field :item_cont %>
  <br>
  <%= f.submit '検索' %>
<% end %>